version: 2

# Generic test steps for most of the unit test targets.
test_steps: &test_steps
  # Composer will be quite a bit happier if unzip is available.
  - run:
      command: |
        apt-get update
        apt-get -y install unzip
      name: Install platform dependencies

  - checkout

  # Now we'll actually install the packages required to test this package.
  - restore_cache:
      keys:
        - v3-{{ .Environment.CIRCLE_JOB }}-dependencies-{{ checksum "composer.json" }}
        - v3-{{ .Environment.CIRCLE_JOB }}-dependencies-

  - run: ./composer.phar install -n --prefer-dist

  - save_cache:
      key: v3-{{ .Environment.CIRCLE_JOB }}-dependencies-{{ checksum "composer.json" }}
      paths:
        - ./vendor

  # Finally, we'll run the unit tests.
  - run: ./composer.phar test-unit

jobs:
  coding_standard:
    docker:
      # Unlike the other test jobs in this file, we'll use CircleCI's PHP image
      # here so we don't have to install Composer separately.
      #
      # Note that the version of PHP doesn't matter here, provided it's a
      # version that PHP_CodeSniffer 3.5 supports (which is PHP 5.4 or newer).
      - image: cimg/php:8.1

    # The coding standard job shares some concepts with the test_steps defined
    # above, but is defined separately due to YAML's inability to merge lists.
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-cs-dependencies-{{ checksum "composer.json" }}
            - v3-cs-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v3-cs-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: composer cs

  "php-8.1":
    docker:
      - image: php:8.1-cli

    steps: *test_steps

  integration:
    docker:
      - image: cimg/php:8.1-cli

    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-integration-dependencies-{{ checksum "composer.json" }}
            - v3-integration-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v3-integration-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - restore_cache:
          keys:
            - v3-integration-server-{{ checksum "tests/integration/server/composer.lock" }}
            - v3-integration-server-

      - run: composer install -d tests/integration/server --prefer-dist

      - save_cache:
          key: v3-integration-server-{{ checksum "tests/integration/server/composer.lock" }}
          paths:
            - ./tests/integration/server/vendor

      - restore_cache:
          keys:
            - v3-integration-v3-{{ checksum "tests/integration/v1/composer.lock" }}
            - v3-integration-v3-

      - run: composer install -d tests/integration/v1 --prefer-dist

      - save_cache:
          key: v3-integration-v3-{{ checksum "tests/integration/v1/composer.lock" }}
          paths:
            - ./tests/integration/v3/vendor

      - run:
          command: composer test-integration
          name: Monolog 3 integration tests
          working_directory: tests/integration/v3

workflows:
  version: 2
  test:
    jobs:
      - coding_standard
      - "php-8.1":
          requires:
            - coding_standard
      - integration:
          requires:
            - coding_standard
